### ISSUE TITLE
佬，为啥我只能--lang=CHS，其他语言就都不行0.0

### ISSUE THREAD

**Issue by RORY377** [mrzjy/StarrailDialog#1]
![image](https://github.com/mrzjy/StarrailDialog/assets/151196763/18ac3694-498a-4f69-b536-5298b0214e2e)

**Comment by mrzjy** [comment]
增加了一个 try catch，重新 pull 一下代码吧，现在应该没问题了，1055921152 这个 key 貌似只有中文 text map 才有。。不过问题不大，忽略掉就行
